server:
  port: 9999
  tomcat:
    max-connections: 30000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://146.56.203.251:3306/code_scaffold?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    username: mysql
#    password: passWord2024
    url: jdbc:mysql://localhost:3306/student_grades?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 3.14
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
ip: localhost
